/** Adapters */
export const adaptersIdsMap = {
  VOTING_ADAPTER: "voting",
  ONBOARDING_ADAPTER: "onboarding",
  NONVOTING_ONBOARDING_ADAPTER: "nonvoting-onboarding",
  TRIBUTE_ADAPTER: "tribute",
  FINANCING_ADAPTER: "financing",
  MANAGING_ADAPTER: "managing",
  RAGEQUIT_ADAPTER: "ragequit",
  GUILDKICK_ADAPTER: "guildkick",
  CONFIGURATION_ADAPTER: "configuration",
  DISTRIBUTE_ADAPTER: "distribute",
  TRIBUTE_NFT_ADAPTER: "tribute-nft",
  TRANSFER_STRATEGY_ADAPTER: "erc20-transfer-strategy",
  DAO_REGISTRY_ADAPTER: "daoRegistry",
  BANK_ADAPTER: "bank",
  ERC721_ADAPTER: "nft",
  ERC1155_ADAPTER: "erc1155-adpt",
  ERC1271_ADAPTER: "signatures",
  SNAPSHOT_PROPOSAL_ADAPTER: "snapshot-proposal-adpt",
  VOTING_HASH_ADAPTER: "voting-hash-adpt",
  KICK_BAD_REPORTER_ADAPTER: "kick-bad-reporter-adpt",
  COUPON_ONBOARDING_ADAPTER: "coupon-onboarding",
  KYC_ONBOARDING_ADAPTER: "kyc-onboarding",
  NFT_ADAPTER: "nft-adapt",
  ERC20_TRANSFER_STRATEGY_ADAPTER: "erc20-transfer-strategy",
  REIMBURSEMENT_ADAPTER: "reimbursement",
  UNAGII_VAULT_DEPOSIT_ADAPTER: "vault-deposit-adpt",
  UNAGII_VAULT_WITHDRAW_ADAPTER: "vault-withdraw-adpt",
  MOVEMENT_ADAPTER: "movement-adpt",
  INTIATIVE_ADAPTER: "intiative-adpt",
  VETOER_ADAPTER: "vetoer-adpt",
  SERVICE_PROVIDER_ADAPTER: "service-provider-adpt",
  UNISWAP_SUB_POOL_V3_ADAPTER: "uniswapV3-subpool-adpt",
  UNISWAP_ADD_POOL_V3_ADAPTER: "uniswapV3-addpool-adpt",
  UNISWAP_SUB_POOL_ADAPTER: "uniswap-subpool-adpt",
  UNISWAP_ADD_POOL_ADAPTER: "uniswap-addpool-adpt",
  SUSHISWAP_ADD_POOL_ADAPTER: "sushiswap-addpool-adpt",
  SUSHISWAP_SUB_POOL_ADAPTER: "sushiswap-subpool-adpt"
};

/** Extensions */
export const extensionsIdsMap = {
  BANK_EXT: "bank",
  ERC1271_EXT: "erc1271",
  ERC721_EXT: "nft",
  EXECUTOR_EXT: "executor-ext",
  VESTING_EXT: "internal-token-vesting-ext",
  ERC1155_EXT: "erc1155-ext",
  ERC20_EXT: "erc20-ext",
  BONDING_CURVE_EXT: "bonding-curve",
  BANCOR_EXT: "bancor-formula",
  ENDOWMENT_EXT: "endowment-bank"
};
